prooph/event-store

src/Prooph/EventStore/Aggregate/AggregateRepository.php, src/Prooph/EventStore/Aggregate/AggregateType.php, src/Prooph/EventStore/Aggregate/DefaultAggregateTranslator.php, src/Prooph/EventStore/Configuration/Configuration.php, src/Prooph/EventStore/EventStore.php, src/Prooph/EventStore/Stream/AggregateStreamStrategy.php, src/Prooph/EventStore/Stream/AggregateTypeStreamStrategy.php, src/Prooph/EventStore/Stream/EventId.php, src/Prooph/EventStore/Stream/EventName.php, src/Prooph/EventStore/Stream/MappedSuperclassStreamStrategy.php, src/Prooph/EventStore/Stream/SingleStreamStrategy.php, src/Prooph/EventStore/Stream/Stream.php, src/Prooph/EventStore/Stream/StreamEvent.php, src/Prooph/EventStore/Stream/StreamName.php, tests/Prooph/EventStoreTest/Aggregate/AggregateRepositoryTest.php, tests/Prooph/EventStoreTest/Feature/FeatureManagerTest.php, tests/Prooph/EventStoreTest/Stream/AggregateStreamStrategyTest.php, tests/Prooph/EventStoreTest/Stream/AggregateTypeStreamStrategyTest.php, tests/Prooph/EventStoreTest/Stream/MappedSuperclassStreamStrategyTest.php, tests/Prooph/EventStoreTest/Stream/SingleStreamStrategyTest.php
+ performance improvment by replacing assertion chains with static assertion calls
=> Simplified aggregate repo

src/Prooph/EventStore/EventStore.php, tests/Prooph/EventStoreTest/EventStoreTest.php
This PR adds nested transaction support to the event store and closes #41
=> patch-41: Support nested transactions

src/EventStore.php, tests/bootstrap.php, tests/phpunit.xml.dist
=> Mark nested transactions as deprecated

src/Adapter/AdapterMessageConverter.php, src/Adapter/Exception/RuntimeException.php, src/Adapter/PayloadSerializer.php, src/Adapter/PayloadSerializer/JsonPayloadSerializer.php, tests/Adapter/AdapterMessageConverterTest.php, tests/Adapter/PayloadSerializer/JsonPayloadSerializerTest.php, tests/Configuration/ConfigurationTest.php, tests/Mock/AdapterMessageConverterMock.php
=> Add AdapterMessageConverter trait and a payload serializer

src/Container/EventStoreFactory.php, src/Container/Stream/AggregateStreamStrategyFactory.php, src/Container/Stream/AggregateTypeStreamStrategyFactory.php, src/Container/Stream/SingleStreamStrategyFactory.php, src/Service/EventStoreFactory.php
see: https://github.com/prooph/event-store/issues/69
=> Move EventStoreFactory one namespace level up

src/Aggregate/AggregateRepository.php, tests/Aggregate/AggregateRepositoryTest.php, tests/Feature/FeatureManagerTest.php
see: https://github.com/prooph/event-store/issues/72
=> Change constructor signature of AggregateRepository

README.md, src/Container/EventStoreFactory.php, src/EventStore.php, src/Plugin/Plugin.php, tests/Mock/EventLoggerPlugin.php, tests/Plugin/PluginManagerTest.php
see: https://github.com/prooph/event-store/issues/75
=> Rename Features to Plugins

phpunit.xml.dist, src/Container/EventStoreFactory.php, src/Container/Stream/AggregateStreamStrategyFactory.php, src/Container/Stream/AggregateTypeStreamStrategyFactory.php, src/Container/Stream/SingleStreamStrategyFactory.php, tests/Container/EventStoreFactoryTest.php, tests/Container/Stream/AggregateStreamStrategyFactoryTest.php, tests/Container/Stream/AggregateTypeStreamStrategyFactoryTest.php, tests/Container/Stream/SingleStreamStrategyFactoryTest.php
see: https://github.com/prooph/event-store/issues/70
=> Add factory tests

.php_cs, README.md, docs/event_store.md, docs/repositories.md, examples/event/QuickStartSucceeded.php, examples/quickstart.php
=> Restructure and improve documentation

src/Aggregate/AggregateRepository.php, src/Aggregate/AggregateTranslator.php, src/Aggregate/ConfigurableAggregateTranslator.php, tests/Aggregate/ConfigurableAggregateTranslatorTest.php, tests/Mock/DefaultAggregateRoot.php, tests/Mock/DefaultAggregateRootContract.php, tests/Mock/FaultyAggregateRoot.php, tests/Mock/User.php
it applies events to aggregate roots only after they are written to the event stream
=> apply events late

src/Aggregate/AggregateRepository.php, tests/Aggregate/AggregateRepositoryTest.php
see: https://github.com/prooph/event-store/issues/99
=> Improve pendingEvents index

src/Adapter/Adapter.php, src/Adapter/InMemoryAdapter.php, src/EventStore.php, src/Util/CompositeIterator.php, tests/Adapter/InMemoryAdapterTest.php, tests/EventStoreTest.php, tests/Mock/Post.php, tests/Mock/PostCreated.php, tests/Mock/TestIteratorAggregate.php, tests/Util/CompositeIteratorTest.php
solves: https://github.com/prooph/event-store/issues/13
=> Replay functionality

README.md, docs/upcasting.md
=> Upcasting the right way

README.md, docs/apply_events_late.md, docs/repositories.md, src/Aggregate/ConfigurableAggregateTranslator.php
=> Some info about apply events late

composer.json, src/Container/EventStoreFactory.php, tests/Container/EventStoreFactoryTest.php
=> Make use of interop config for event store factory

src/Aggregate/AggregateRepository.php
see example here: https://gist.github.com/prolic/a320d43ee1ca709384fb
=> patch aggregate repository to allow inheritance aggregate roots

src/EventStore.php
solves: https://github.com/prooph/event-store/issues/158
=> set recordedEvent back to ArrayIterator when rolling back transaction

docs/event_store.md, src/Metadata/MetadataEnricher.php, src/Metadata/MetadataEnricherAggregate.php, src/Metadata/MetadataEnricherPlugin.php, tests/Metadata/MetadataEnricherAggregateTest.php, tests/Metadata/MetadataEnricherPluginTest.php
=> Metadata enricher

docs/interop_factories.md, src/Container/EventStoreFactory.php, tests/Container/EventStoreFactoryTest.php
=> Setup metadata_enrichers option in event store factory

src/Adapter/Adapter.php, src/Exception/ConcurrencyException.php
fixes: https://github.com/prooph/event-store/issues/172
=> add concurrency exception

.gitattributes
=> Ignore some directories in the dist package

src/Aggregate/AggregateRepository.php, tests/Aggregate/AggregateRepositoryTest.php
I feel you do not understand me - or me you - hope this helps
fix for #179
=> Multiple repo get calls sametransaction same instance

src/Adapter/InMemoryAdapter.php, src/Metadata/MetadataMatcher.php, src/Metadata/Operator.php, tests/Adapter/InMemoryAdapterTest.php
- add new NOT_EQUALS operator
- allow specifying a key twice
=> improve metadata matcher

examples/quickstart.php, src/AbstractActionEventEmitterEventStore.php, src/ActionEventEmitterEventStore.php, src/Container/InMemoryEventStoreFactory.php, src/EventStore.php, src/InMemoryEventStore.php, src/Metadata/Operator.php, src/TransactionalActionEventEmitterEventStore.php, tests/InMemoryEventStoreTest.php, tests/Metadata/MetadataEnricherPluginTest.php, tests/TestCase.php
resolves: https://github.com/prooph/event-store/issues/225
=> add updateStreamMetadata method to event store

examples/quickstart.php, src/ActionEventEmitterEventStore.php, src/Container/InMemoryEventStoreFactory.php, src/Metadata/MetadataEnricherPlugin.php, src/Plugin/AbstractPlugin.php, tests/ActionEventEmitterEventStoreTest.php, tests/Container/InMemoryEventStoreFactoryTest.php, tests/Metadata/MetadataEnricherPluginTest.php, tests/Mock/EventLoggerPlugin.php, tests/Plugin/PluginManagerTest.php
see: https://github.com/prooph/event-store/issues/232
=> update plugin registration

src/EventStore.php, src/ReadOnlyEventStore.php
resolves: https://github.com/prooph/event-store/issues/250
=> add ReadOnlyEventStore interface

examples/quickstart.php, src/ActionEventEmitterEventStore.php, src/InMemoryEventStore.php, src/Metadata/MetadataEnricherPlugin.php, src/Projection/InMemoryEventStoreProjection.php, src/Projection/InMemoryEventStoreQuery.php, src/Projection/InMemoryEventStoreReadModelProjection.php, src/ReadOnlyEventStore.php, tests/ActionEventEmitterEventStoreTest.php, tests/InMemoryEventStoreTest.php, tests/Metadata/MetadataEnricherPluginTest.php, tests/Mock/EventLoggerPlugin.php, tests/Projection/InMemoryEventStoreProjectionTest.php
resolves https://github.com/prooph/event-store/issues/252
=> Change EventStore::load / loadReverse methods

src/ActionEventEmitterEventStore.php, src/InMemoryEventStore.php, src/ReadOnlyEventStore.php
resolves https://github.com/prooph/event-store/issues/271
/cc @oqq
=> Remove PHP_INT_MAX constant from interface

README.md, docs/event_store.md, docs/interop_factories.md, src/Container/InMemoryEventStoreFactory.php, src/ReadOnlyEventStoreWrapper.php, tests/Container/InMemoryEventStoreFactoryTest.php, tests/Plugin/PluginManagerTest.php, tests/ReadOnlyEventStoreWrapperTest.php
=> add read only event store wrapper

src/InMemoryEventStore.php, src/Metadata/FieldType.php, src/Metadata/MetadataMatcher.php, src/Metadata/Operator.php, tests/AbstractEventStoreTest.php, tests/Metadata/MetadataMatcherTest.php
- add new metadata matcher operators
- add message property matching
resolves https://github.com/prooph/event-store/issues/284
pdo-event-store updates needed before release
=> Support message property filters + new operators

tests/TransactionalEventStoreTestTrait.php
see: https://github.com/prooph/pdo-event-store/issues/84
=> add test it_loads_and_saves_within_one_transaction

src/InMemoryEventStore.php
found this bug in InMemoryEventStore, but didn't found a suitable test-case yet.
=> fix InMemoryEventStore

src/Upcasting/UpcastingIterator.php, tests/Upcasting/UpcastingIteratorTest.php
=> Fixed compability issues EmptyIterator

README.md
If this PR is accepted I'll go through all repos and just update the README (without PRs) accordingly.
=> Link to SO

tests/Projection/AbstractProjectionManagerTest.php, tests/Projection/InMemoryProjectionManagerTest.php
see: https://github.com/prooph/pdo-event-store/issues/138
/cc @oqq
=> add test cases for multiple calls to reset/stop/delete projection

src/Projection/InMemoryEventStoreProjector.php, src/Projection/InMemoryEventStoreQuery.php, src/Projection/InMemoryEventStoreReadModelProjector.php, src/Projection/InMemoryProjectionManager.php, tests/Projection/InMemoryEventStoreProjectorTest.php, tests/Projection/InMemoryEventStoreQueryTest.php, tests/Projection/InMemoryEventStoreReadModelProjectorTest.php, tests/Projection/InMemoryProjectionManagerTest.php
=> allows NonTransactionalInMemoryEventStore for projections

src/ResolvedEvent.php
Ref https://github.com/prooph/event-store-http-client/issues/32
=> Improve docblocks of ResolvedEvent

composer.json, src/Util/Assertion.php
=> Fix incompatibility of Util\Assertion with beberlei/assert v3.2.3

.travis.yml, composer.json, src/Async/Projections/ProjectionsManager.php, src/Projections/ProjectionsManager.php
Resolves https://github.com/prooph/event-store/issues/366
=> Emit enabled inconsistency

src/Projections/ProjectionDetails.php
=> Fix ProjectionDetails

src/ListenerHandler.php
@prolic First issue I found when trying to fix the tests in https://github.com/prooph/event-store-client/pull/112. Merge pls and then restart the tests on your PR.
=> Fix Closure in ListenerHandler

composer.json
Reverts prooph/event-store#387
see https://github.com/ramsey/uuid/issues/314
=> Revert "Update ramsey/uuid requirement from ^3.8 to ^3.8 || ^4.0"

src/Async/EventStoreCatchUpSubscription.php, src/Async/Projections/ProjectionsManager.php, src/EventStoreCatchUpSubscription.php
=> ProjectionManager can now return ValueObject when asking for status

src/Async/Projections/ProjectionsManager.php, src/Async/Projections/QueryManager.php, src/Projections/ProjectionStatistics.php, src/Projections/ProjectionsManager.php, src/Projections/Query.php, src/Projections/QueryManager.php, src/Projections/State.php
resolves prooph/event-store#401
=> removing json strings
